name: Deploy Dev Environment

on:
  push:
    branches:
      - dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Dev Environment
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Update Azure CLI to latest version
      - name: Update Azure CLI
        run: |
          az upgrade --yes

      # Configure Node.js version on App Service
      - name: Configure Node.js version
        run: |
          az webapp config appsettings set --name patch-main-app --resource-group patch-nextjs-app --settings WEBSITE_NODE_DEFAULT_VERSION=~22

      # Create dev deployment slot if it doesn't exist
      - name: Create dev deployment slot if needed
        run: |
          # Check if the dev slot exists
          DEV_SLOT_EXISTS=$(az webapp deployment slot list --name patch-main-app --resource-group patch-nextjs-app --query "[?name=='dev']" -o tsv)

          if [ -z "$DEV_SLOT_EXISTS" ]; then
            echo "Creating new dev deployment slot..."
            az webapp deployment slot create \
              --name patch-main-app \
              --resource-group patch-nextjs-app \
              --slot dev \
              --configuration-source patch-main-app
            
            # Configure Node.js version for the new slot
            az webapp config appsettings set \
              --name patch-main-app \
              --resource-group patch-nextjs-app \
              --slot dev \
              --settings WEBSITE_NODE_DEFAULT_VERSION=~22
            
            echo "Dev deployment slot created and configured."
          else
            echo "Dev deployment slot already exists."
          fi

      # Deploy to the dev slot
      - name: Deploy to dev slot
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'patch-main-app'
          resource-group-name: 'patch-nextjs-app'
          slot-name: 'dev'
          package: .
          startup-command: 'npm start'

      # Set up custom hostname for the dev slot
      - name: Configure custom hostname
        run: |
          HOSTNAME="dev.staging.robruizr.dev"

          # Check if hostname binding exists
          BINDING=$(az webapp config hostname list --webapp-name patch-main-app --slot dev --resource-group patch-nextjs-app --query "[?name=='$HOSTNAME'].name" -o tsv)

          if [ -z "$BINDING" ]; then
            # Add hostname binding
            echo "Attempting to add custom domain binding. This may fail if DNS is not configured yet."
            az webapp config hostname add --webapp-name patch-main-app --slot dev --resource-group patch-nextjs-app --hostname $HOSTNAME || echo "Custom domain binding failed. Please configure DNS records first."
          fi
        continue-on-error: true # Allow workflow to continue even if this step fails

      - name: Log out from Azure
        run: az logout
        if: always()
